apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: internal-nginx-letsencrypt-stage
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: yongwoo@crowdworks.kr
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
     name: internal-nginx-letsencrypt-stage
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
       ingress:
         class: internal-nginx
